version: 3

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD:
    networks:
      - default
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD:
      LETSENCRYPT_HOST: 
      VIRTUAL_HOST: 
    ports:
      expose:
        - '80'
        - '443'
    networks:
      - nextcloud_proxy-tier
      - default
    depends_on:
      - postgres
networks:
  nextcloud_proxy-tier:
    external: true
  default:
volumes: 
  postgres_data:
